### ISSUE TITLE
Thema ffn wird nicht abgespielt bzw wird nach kurzem anspielen gewechselt

### ISSUE THREAD

**Issue by kle99** [Acer54/Webradio_v2#11]
Die Anweisung um in jessie den mpd von 0.19.1 auf mpd 0.19.21 zu aktualisieren, 
https://github.com/Acer54/Webradio_v2/wiki/FAQ#thema-ffn-wird-nicht-abgespielt-bzw-wird-nach-kurzem-anspielen-gewechselt
funktionieren nicht mehr. Das sind die Ausgaben:
`sudo touch /etc/apt/sources.list.d/backports.list`
`sudo bash -c 'echo "deb ftp://ftp.nl.debian.org/debian jessie-backports main contrib non-free" > /etc/apt/sources.list.d/backports.list'`
`gpg --keyserver pgpkeys.mit.edu --recv-key 8B48AD6246925553`
`gpg: requesting key 46925553 from hkp server pgpkeys.mit.edu`
`gpgkeys: key 8B48AD6246925553 can't be retrieved`
`gpg: no valid OpenPGP data found.`
`gpg: Total number processed: 0`
Kann mir jemand helfen?

**Comment by Acer54** [comment]
Ich habe [hier](https://raspberrypi.stackexchange.com/questions/12258/where-is-the-archive-key-for-backports-debian-org) eine mögliche Antwort auf dieses Problem gefunden (letzter Beitrag).

Bitte mal testen und rückmelden, dann werde ich das Wiki entsprechend updaten.

MFG, Matthias

**Comment by kle99** [comment]
Hallo Matthias,
ich habe die Zeilen 3 und 4 geändert.
- man muß 2 Schlüssel holen
- "gpg -a --export..." ist nicht erforderlich
neue Zeilen 3 und 4:
`sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 8B48AD6246925553`
`sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 7638D0442B90D010`

für Dich die Ausgabe der Kommandos:
---------------------------------------
`# hole key 8B48AD6246925553`
`​sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 8B48AD6246925553`
`Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.OmHXeJncv1 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --recv-key --keyserver keyserver.ubuntu.com 8B48AD6246925553`
`gpg: requesting key 46925553 from hkp server keyserver.ubuntu.com`
`gpg: key 46925553: "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" not changed`
`gpg: Total number processed: 1`
`gpg:              unchanged: 1`
`​#`
`# hole key 7638D0442B90D010`
​`sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 7638D0442B90D010`
`Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.h6DGw31ekl --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --recv-key --keyserver keyserver.ubuntu.com 7638D0442B90D010`
`gpg: requesting key 2B90D010 from hkp server keyserver.ubuntu.com`
`gpg: key 2B90D010: public key "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>" imported`
`gpg: Total number processed: 1`
`gpg:               imported: 1  (RSA: 1)`
---------------------------------------
Grüße Klaus

**Comment by kle99** [comment]
Hallo Mathias,

- Das Problem ist mit dem update auf mpd 0.19.21 behoben.
- Wie gesagt, ich habe beide gepostete Schlüssel gebraucht

Schönen Gruß, Klaus
