### ISSUE TITLE
Fehlschlag beim holen des Paketes

### ISSUE THREAD

**Issue by Phanthomas83** [Acer54/Webradio_v2#16]
habe das alte webradio stillgelegt und wollte jetzt wie du es beschrieben hast installieren.
zuerst gab es probleme mit https, konnte aber gelöst werden.
beide wget-aufrufe funktionierten auch.
nur ab sudo apt update komme ich nicht weiter.
fehlermeldung:
`W: Fehlschlag beim Holen von https://raw.githubusercontent.com/Acer54/repository/master/release/./Packages  Ungültige Kopfzeile

E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.`

manuelle installation via download der *.deb-datei funktioniert ebenfalls nicht, 

`E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »point-rpi« konnte nicht gefunden werden.
E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »pprompt« konnte nicht gefunden werden.
E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »raspberrypi-ui-mods« konnte nicht gefunden werden.
E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »rc-gui« konnte nicht gefunden werden.
E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »libupnpp4« konnte nicht gefunden werden.
E: Veröffentlichung »webradio-py_0.3.5_all.deb« für »libupnpp4-dev« konnte nicht gefunden werden.`
Das ist nur ein Auszug  der Fehlermeldung...

**Comment by Acer54** [comment]
Hallo @Phanthomas83, ich habe grade meinen Webradio hier angeworfen um zu sehen, ob ich das Repo nicht durch die letzten Updates gekillt habe... dem ist jedoch nicht so. Ich habe auch relativ aktuelle Rückmeldungen von anderen Nutzen die das Repo benutzt haben und wo es geklappt hat. 

Da bei dir allerdings auch die manuelle Installation nicht funktioniert (weil er einen Haufen benötigter Abhängigkeiten nicht laden kann, die allerdings durch andere Paketquellen kommen sollten) würde ich sagen, dass entweder mit deiner Installation etwas schiefgegangen ist, oder diese noch nicht abgeschlossen ist.

Du kannst das Repo wieder entfernen mittels: 
`sudo rm -f  /etc/apt/sources.list.d/acer54_repository.list` 

Ein anschließendes update deiner Paketquellen mittels `sudo apt update` muss funktionieren. (Falls dies so ist, mach erst einmal ein update des kompletten systems.... (sudo apt dist-upgrade))

**Comment by Acer54** [comment]
Da fällt mir noch ein Fehler-Szenario ein, das mit deinem https-Problem zusammenhängen könnte... vielleicht hat apt einen korrupten Cache, evtl. verursacht durch fehlgeschlagene Update-Versuche während deines https-Problems... diese könntest du löschen mit
`sudo rm /var/lib/apt/lists/* -vf`
Beim anschließenden Update (sudo apt update) werden alle Release-Dateien neu heruntergeladen. Vielleicht löst das dein Problem. Erst wenn ein Update mal erfolgreich durchgelaufen ist, würde ich versuchen webradio-py zu installieren...

**Comment by Phanthomas83** [comment]
hab mal eine neue sd-karte genommen, stretch mit desktop und 4.14-kernel installiert, alles updates / upgrades ausgeführt, noch pakete (python) installiert, damit webradio-py installiert werden kann.
zumindest läuft das programm jetzt aller paar bootvorgänge reibungslos.
was passiert sonst:
unerwartete neustarts, teilweise während des bootens. 
wenn es mal läuft bilden sich schlieren auf dem display (was vorher in der alten webradio-version problemlos ging), sodass nichts mehr erkennbar ist (via vnc ist aber alles bestens).
auch eine andere raspi-platine gleichen typs hilft da nicht...

benutzt wird ein pi 3b v1.2, hifiberry amp+ 1.0, ein touchscreen (den es auf amazon nimmer gibt).
wollte eigentlich nur auf die neue version deines radios upgraden, in der hoffnung, dass die netzwerkeinbindung wieder reibungslos klappt (ornder und inhalt via fstab sichtbar, ABER nicht immer landet alles in der playlist)

**Comment by Acer54** [comment]
dass das an der "neuen" Version liegt ist leider recht unwahrscheinlich. Der einzige Unterschied zwischen den letzten Versionen sind kleine Logik-Bugfixes und der Installer, der halbautomatisch den Installationsprozess führt. Hier sollte sich nichts in Verbindung mit "Schlieren(?)" im Display getan haben.
Deine beschriebenen Themen bzgl. "Netzwerkverbindung" usw. haben auch nichts mit webradio-py zu tun, da webradio-py deutlich später, mit der GUI gestartet wird... 
Webradio-py ist mehr oder weniger ein "dummes" Script, das als Art grafische Oberfläche für MPD her hält, mehr auch nicht. 

Bzgl. Netzwerkverbinding hatte ich ab Stretch auch akute Probleme mit der fstab. Leider hat das plötzlich alles nicht mehr so wirklich geklappt, wie es das früher einmal tat. Daher empfehle ich dir, dich am [Artikel im Wiki](https://github.com/Acer54/Webradio_v2/wiki/4_Include-external-storages-de-DE#einbinden-eines-netzwerk-speicher-nas) zu halten und einmal systemd an der Stelle der fstab zu nutzen. Vielleicht liegt da der Hund für deine fehlerhaften Boots begraben.

Was mich allerdings völlig ratlos macht, sind die Grafik-Probleme die du beschreibst. Es gibt mittlerweile hunderte von Nachbauten. Mit bestimmt 50 -60 davon habe ich immer wieder mal Kontakt bzgl. ein paar Kleinigkeiten... aber von solch massiven Grafikproblemen habe ich noch nie gehört.

P.S.: Ich bin mir sicher, du hast schon mal in die Log-Dateien von webradio-py gesehen oder ? (~/.webradio/webradio.log(1))

**Comment by Phanthomas83** [comment]
ok, hab den fehler gefunden -.-
der pi brauchte noch eine zweite stromquelle...
bisher betrieb ich ihn über den hifiberry, jetzt zusätzlich via microusb.
eins habe ich noch:
ich habe einen netzwerkordner erfolgreich gemounted. kann auch darauf zugreifen, webradio sieht den ordner und den inhalt auch. aber die markierten lieder werden nicht in die playlist übernommen...

**Comment by Acer54** [comment]
Webradio benutzt eine Art Dateibrowser, der unabhängig von der Indexierung funktioniert.
Damit die Titel in die Playlist aufgenommen werden, muss folgendes gegeben sein:

1. Der Ordner in dem das Netzlaufwerk gemountet ist, muss in deinen Musik-Ordner, den du bei der Installation angegeben hast mittels Soft-link verknüpft sein.
2. Dein Musik-Ordner muss vollständig Indexiert worden sein, zu einer Zeit in der das Netzlaufwerk auch gemountet war
3. Das Indexieren (was bei größeren Dateimengen durchaus bis zu einer Stunde dauern kann) muss abgeschlossen sein.

Nach zu lesen im [Wiki](https://github.com/Acer54/Webradio_v2/wiki/4_Include-external-storages-de-DE)

Eventuelle Fehlermeldungen, können in der Datei ~/.webradio/webradio.log(1) nachgelesen werden.

Ist der initiale Bug-Report damit abgeschlossen? Wenn ja, würde ich diesen gerne schließen und dich bitten für andere Themen, einen neuen Report zu eröffnen, um das Ganze etwas übersichtlich zu halten und eventuell anderen Usern hiermit weiter zu helfen.

Gruß
Matthias
