### ISSUE TITLE
MP3-Dateien hängen ab und zu kurz

### ISSUE THREAD

**Issue by Phanthomas83** [Acer54/Webradio_v2#18]
hab zum genannten Problem noch nix im FAQ gefunden,
der Buffer von mpd wurde schon auf 
audio_buffer_size       "4096"
buffer_before_play      "100%"
angehoben (# am anfang der zeile entfernt).
dennoch kommt es dann und wann (eigentlich bei jedem lied) via wlan zu "hängern".
verbindung via wlan ist jedoch sehr gut, da der accesspoint nur einen raum weiter ist (wlanstärke laut pi: um die 86%).
gibt es bei mpd noch weitere einstellungen zwecks puffer, oder sollte ich mal etwas mehr als 4096 ausprobieren?

grüße :-)

**Comment by Phanthomas83** [comment]
etwas rumexperimentieren später:
audio buffer size auf übertriebene 16mb (16384) eingestellt... radiosender brauchen jetzt fast 20 sekunden, aber dafür bricht bisher keine mp3 mehr ab bzw. "ruckelt / hängt".
wollte auch noch testen, wenn generelle 1 gb (oder beliebig andere größe) reserviert werden via
input_cache {
size "1 GB"
}
aber da stürzt das webradio ab und startet das programm in einer dauerschleife immer neu.

kann im prinzip geschlossen werden...

**Comment by Acer54** [comment]
Mein Tip wäre hier eher Richtung Hardware:

- Zu hohe Last, verursacht durch andere Prozesse die parallel laufen (?)
- Lese-/Schreibgeschwindigkeit auf die Micro-SD Karte (schon eine Class 10 verwendet?)
- Wlan Abbrüche verursacht durch Stromschwankungen (bei Verwendung eines USB-WiFi-Dongls) > Netzteil zu schwach, nicht entstöhrt, evtl. zusätzlicher Stromkonsument an den USB-Ports? 

Was benutzt du für Hardware? Was hast du für Peripherie in Verwendung?

**Comment by Phanthomas83** [comment]
benutzt wird ein pi 3b, sonstige Nebenprozesse gibt es nicht, nur das webradio.
onboard wifi wird genutzt, wollte lan über z.b. powerlan/dlan umgehen.
Stromversorgung ist mit über 2 ampere eigentlich genügend. die auslastung der cpu ist minimal (unter 20% ca.).
eine klasse 10 sd-karte wird verwendet (32 gb, davon ~22gb frei).
an den usb ports hängt der touchscreen, hifiberry wird seperat mit strom gefüttert, sonst stirbt der Touchscreen ab und das pi startet spontan neu (soll man laut hifiberry nicht machen, aber ich habe dahingehend bisher nichts negatives erfahren können).

denke mal, dass ich für mich etwas mehr als 4mb an buffer nutzen muss (vielleicht reichen auch 8mb statt der jetzigen 16mb buffer).

würde diesen Fall dennoch schließen lassen, da bis jetzt alles wieder ordentlich funktioniert.

**Comment by Acer54** [comment]
Kannst trotzdem mal versuchen den USB current zu erhöhen:
Man öffnet die Datei `sudo nano /boot/config.txt` mit Root-Rechten und fügt den Parameter `max_usb_current=1` am Ende hinzu.
Damit ist die (softwareseitige) Limitierung von 600mA (für alle USB Ströme zusammengerechnet!!) auf 1200mA erhöht. (Neustart erforderlich).
Ich hatte mit grenzwertigen Stromversorgungen (speziell wenn etwas "hungriges" an den Ports hing) schon die dollsten Probleme.
In diesem Fall geht probieren über studieren.

Ich habe deinen Report auch mal zum Anlass genommen und dieses Thema im Wiki bei der "Verwendung von externen Speichermedien" angebracht.
