### ISSUE TITLE
Mute and Power Icons not customizable

### ISSUE THREAD

**Issue by HiranChaudhuri** [Acer54/Webradio_v2#22]
I followed the fine manual for own designs (https://github.com/Acer54/Webradio_v2/wiki/6_Own-Designs) and must say it is very well written. Most of the time for customization went into finding nice icons or deciding on colours.

The only thing that sticks out is the fact the mute and power icons are not customizable. In Grunge, Fallback or Gold designs this does not hurt as their colour somehow matches. However in Blue design (and also the one I created) the orange colour just does not match.

I could easily change those icons but then they would just match my new theme. How difficult is it to make those two items part of a design?

**Comment by HiranChaudhuri** [comment]
![design-blue](https://user-images.githubusercontent.com/6866487/64852273-562fa400-d619-11e9-9780-cb57e9a374e1.png)

![design-girly](https://user-images.githubusercontent.com/6866487/64852284-5af45800-d619-11e9-8f08-01e0db8b6c46.png)

**Comment by Acer54** [comment]
With 0.3.9, these 2 Icons are included in the "fallback-theme" and therefor editable.

**Comment by HiranChaudhuri** [comment]
I am not sure whether this one works - at least for me it does not. However I performed several steps at which I do not feel 100% confident to have them done right:

1) merge your new release
2) modify my theme to include the two new buttons as animated GIFs
3) prepare and deploy my theme (this time with all the application changes)

Would you mind taking a look at https://github.com/HiranChaudhuri/Webradio_v2/tree/girlyTheme ?

**Comment by HiranChaudhuri** [comment]
With the latest changes the buttons are customizable. Thank you.

![2019-09-18-110131_800x480_scrot](https://user-images.githubusercontent.com/6866487/65143977-8ced2c00-da16-11e9-881e-b9f841041198.png)
