### ISSUE TITLE
Webradio on official Raspbery Touchscreen (800x480) issue

### ISSUE THREAD

**Issue by HiranChaudhuri** [Acer54/Webradio_v2#23]
I use a Pi Model 3B+ with the official touchscreen (https://www.raspberrypi.org/products/raspberry-pi-touch-display/). It has a resolution of 800x480 pixels.

Webradio works flawlessly on that display apart from the onscreen keyboard.
So searching in the music database reveals a keyboard that is barely usable as the buttons overlap each other (either they are too big or too close).
On the other hand searching for radio stations also produces an onscreen keyboard that is different. Although the buttons are close to each other they do not overlap and are much better usable.

Would it be possible to use the same keyboard for both use cases? And maybe make that customizable via designs as well?

**Comment by HiranChaudhuri** [comment]
![keyboard-media](https://user-images.githubusercontent.com/6866487/64852210-3b5d2f80-d619-11e9-94f4-3d427fd8e44c.png)

![keyboard-radio](https://user-images.githubusercontent.com/6866487/64852228-41eba700-d619-11e9-9602-79e152fa58c9.png)

**Comment by Acer54** [comment]
With Version 0.3.9, I have added an additional (negative) margin on the lower edge of the QStackedWidget (which keeps all the content). With this, it gets a little bit more space.
![merge](https://user-images.githubusercontent.com/17161393/64980799-e5a7b200-d8ba-11e9-8fe8-d853e6001148.png)

**Comment by HiranChaudhuri** [comment]
There is another layout issue: The album art is too close to the slider. This is only evident for graphics using the full space.

![2019-09-18-104311_800x480_scrot](https://user-images.githubusercontent.com/6866487/65144064-c45bd880-da16-11e9-922f-c5c578b28d60.png)

![2019-09-18-110131_800x480_scrot](https://user-images.githubusercontent.com/6866487/65144071-c9208c80-da16-11e9-9254-891c40cda16b.png)

**Comment by HiranChaudhuri** [comment]
And another one, hard to spot on other themes: The player buttons are too close to the below slider so that the border is clipped.

![2019-09-18-135150_800x480_scrot](https://user-images.githubusercontent.com/6866487/65146225-9a58e500-da1b-11e9-84c0-dd22840b3dfb.png)

**Comment by Acer54** [comment]
Seems like this is due to the change which was necessary because of the virtual keyboard... (in webradio.py)
`# stretch content to lower edge to get more space for content at smaller display sizes , see #23
 self.tabWidget_main.setStyleSheet(_fromUtf8("QStackedWidget{margin:0,-10,0,0;}"))`
The space for all buttons **including the checkbox** for "online-results" over the keyboard in the mediaplayer is very limited with 480 pixels... Can you try to tweak this "margin" value?

**Comment by Acer54** [comment]
Just uploaded updated version (margin = -8 instead of 10) and alignment of the album-art is always "top".
I guess now, we would have a slightly worse behaviour of the keyboard...

**Comment by HiranChaudhuri** [comment]
Thank you. 
I played around with the keyboard layout, and finally I am coming up with two alternatives.
1) make the keyboard smaller so it fits the stackedwidget while still being usable
2) make the keyboard 'pop out' by using a modal dialog, then use more than just the stackedwidget area
Which of them would be preferrable?

For 1) I saved one line as I moved the four control buttons to the spacebar line. To save space I then used the 'DejaVu Sans' font and changed the localization into Unicode characters. Here's a screenshot.

![2019-09-23-134318_800x480_scrot](https://user-images.githubusercontent.com/6866487/65423283-ee433f80-de08-11e9-961d-402572a922f1.png)

**Comment by Acer54** [comment]
I would prefer option one, if it is still usable with the minimum window size (640x480),
Would not "hide" this checkbox in the settings-tab, because one would change it for every different search if necessary...

**Comment by HiranChaudhuri** [comment]
The font was contained in my Raspbian installation - I did not do anything special.
However mentioning this dependency would just ensure it is there even when other things break.

Feel free to merge https://github.com/Acer54/Webradio_v2/pull/34

**Comment by Acer54** [comment]
Have added "fonts-dejavu" to the dependencies of the next version.
I have adjusted the fontsize a little and the space for a "optical feedback" (which is necessary from my point of view...)
Can you test the current version at your LCD?

**Comment by HiranChaudhuri** [comment]
I checked out your current code and deployed it to my Raspberry. Within the raspberry layout the keyboard looks a bit strange. I will list several screenshots and some explanation what I did.

This is when I switch to the search screen for the first time after Webradio startup. Everzthing looks good:

![2019-09-24-214943_800x480_scrot](https://user-images.githubusercontent.com/6866487/65545330-73b41600-df15-11e9-805d-916ed8df8574.png)

This is after pressing some buttons and holding one of them. That one is in pressed state, although after it shrunk back. You can see the buttons do not revert to their original size.

![2019-09-24-214959_800x480_scrot](https://user-images.githubusercontent.com/6866487/65545485-c097ec80-df15-11e9-9151-c12ea4c04a3e.png)

I tried to improve my timing and eventually got this screenshot:

![2019-09-24-215017_800x480_scrot](https://user-images.githubusercontent.com/6866487/65545544-dad1ca80-df15-11e9-85a1-cfd638484468.png)

I do not mind a button growing beyond it's size for optical feedback but it should pop back into it's original state when done. My gut feeling is the mismatch is coming from diverting settings in the stylesheet and Python code.

As in the meantime I started a refactoring it seems the favourites cannot be loaded properly. I do not think we have to tackle a compatibility issue, but Webradio died just for that reason. I'll send a PR to get this stabilized.

**Comment by HiranChaudhuri** [comment]
Another slight glitch I noticed since a while but could not find a reason for:
The fav.png icon has a wrong aspect ratio on the screen. I checked the icon itself but that seems ok. On the screen however it is stretched too much horizontally...

![2019-09-24-220438_800x480_scrot](https://user-images.githubusercontent.com/6866487/65546299-87607c00-df17-11e9-9a49-c6b2be70e275.png)

**Comment by Acer54** [comment]
Ok, hope I have fixed the Button-size issue now ... this is driving me crazy in the meantime... can you check it again? (Updated all Stylesheets and virtualkeyboard...

**Comment by Acer54** [comment]
Aspect ratio of Fav-Label should be fixed as well.

**Comment by HiranChaudhuri** [comment]
I just tried your latest code. Congratulations! Both the keyboard and fav-label have improved. :-)
This issue can be closed now.
