### ISSUE TITLE
Logging configuration improvements

### ISSUE THREAD

**Issue by HiranChaudhuri** [Acer54/Webradio_v2#38]
I modified the logging configuration slightly as the config file format is somewhat clumsy. Have a look at this commit and check logging.conf plus webradio.py lines 121 to 126: 
https://github.com/HiranChaudhuri/Webradio_v2/commit/e6fc9e360897f0fb6622f88720abb5fa8f429ac8#diff-864897eee2617f09b651220926dda2d6L120

The background is that now configuring more loggers and loglevels are one-liners that just happen between lines 30 to 40. A drawback is that the dynamically processed logfile path you implemented may be lost again.

**Comment by Acer54** [comment]
After converting this from json to a python-dict, it should be easily possible to replace the value "file> filename" with the user-dir discovered by the program (if the username is different from "pi").
My idea would be to do this replacement, only if the value of "filename" is an empty string. With this approach, the user would have still the possibility to define a different location (wherever he would want to have his log-file located....) If he do not define anything (empty String) the log fill would go to the user-folder than.
Does this make sense for you as well? This would mean we keep the logger.conf empty in fist-step (only the value "filename" of course) and generate the content during the program startup... but if the user has defined another location we will take it. (The user has to take care by his own, that the filepath is existing and is accessable...)

**Comment by Acer54** [comment]
What do you think of this? https://github.com/Acer54/Webradio_v2/commit/8857dcbb8c2284ccafffef56927976405e22dcc6

- Initially, the filename in logger.conf would be an empty string. If the user does not actively specify a deviating file-path the "standard-filepath" /home/$USER/.webradio/webradio.log" is used.

- If the user defines some path, webradio-py will check if the path exists, if yes it will store its log there 

- If the user defined path is not existing, the program start will be aborted. (not sure about this ... maybe it would be better to just start the program?? But the user wont find a logfile and also I am not sure what the logging module will do in such a case...

**Comment by HiranChaudhuri** [comment]
Sounds like an option. There are two reasons that make me hesitate a bit:

1) it is an unsual pattern. Actually users would define logfiles, but your approach is compatible.
The the only unusuality is if the program calculates the path on its own what the result would be. But if we put the message to the log (before and after the dictConfig) it would be visible on the console at least to make it more obvious

2) I noticed that sometimes when I shutdown the application on the console I can see that closing the logfile did not work. The code does it because the permissions need to be amended, but it expects the file appender to be the second appender. This pattern is not good though.

So my suggestion would be we create a subclass of TimedRollingFileAppender that can be configurable, do your calculation and arrange the permissions. This way the logging functionality stays encapsulated in the logging framework and there is no pingpong in the responsibility of the logfile. If you like that aproach I can prepare such a class and you may fill in the functionality for file permissions and finding the correct path.

**Comment by HiranChaudhuri** [comment]
So it seems I cannot make it work as I suggested. I am facing strange errors and also Google cannot point me to a suitable example.
With that I suggest you just keep what you have so far. It is the best solution that works for us, and if need be we can revisit the topic at a later time.
