### ISSUE TITLE
Can not make work Webradio V2 on LCD 7" Rasberry original

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#42]
Hello.
I install many times directly on Pi 3B+ conected to original LCD but not work.
I suspected the problem after I modified hostname to 'Webradio'.
Where do you think I'm wrong?
The LCD is rated at 800x480 but default on Pi 3B+ is configured at 720x480.
I suspected that this is the problem but I do not know how to configure it.
It try to start but nothing is happed.
Before, I install on TV via HDMI, and it works well.
Can You help me please?

**Comment by Acer54** [comment]
Hello, omulverde,
can you please provide a few further information? 

- What OS version are you running? `cat /etc/os-release`
- Webradio-py is installed? `sudo dpkg -s webradio-py`
- What is the log-file telling? `cat ~/.webradio/webradio.log`
- How do you connect the Pi to your network? eth0 or wifi?

I also do not understand, if it does not work after you have changed your hostname and resolution, or it even havent worked from the beginning (with original installation)?

**Comment by omulverde** [comment]
Before I install Webradio I change hostname. I do not change any resolution of Pi. Default is 720x480 on Rasberry 7" LCD.

**Comment by omulverde** [comment]
1. Linux 10 Buster
2. it is not instaled (I not why)
3. not such file or directory (now I relized that I'm stupid)
4. wifi on 5G frecvency router

Why did not instal it? what is wrong?

**Comment by omulverde** [comment]
root@webradio:~# hostname
webradio
root@webradio:~# apt install webradio-py
Reading package lists... Done
Building dependency tree       
Reading state information... Done
webradio-py is already the newest version (0.3.9).
The following package was automatically installed and is no longer required:
  point-rpi
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@webradio:~# 

...and did not start....

**Comment by omulverde** [comment]
Right now I installed again. The same result: it is not instaled. Hostname is webradio.

**Comment by omulverde** [comment]
root@webradio:/home# ls
pi
root@webradio:/home# ls -al
total 16
drwxr-xr-x  4 root root 4096 Nov 29 21:21 .
drwxr-xr-x 21 root root 4096 Sep 26 03:46 ..
drwxr-xr-x 20 pi   pi   4096 Dec  1 12:51 pi
drwxrwxrwx  2 root root 4096 Nov 29 21:21 .webradio
root@webradio:/home# dpkg -s webradio-py
Package: webradio-py
Status: install ok installed
Priority: optional
Maintainer: Matthias Laumer <matthias.laumer@web.de>
Architecture: armhf
Source: https://github.com/Acer54/Webradio_v3
Version: 0.3.9
Depends: python-six (>= 1.6.1), python-qt4, python-mpd, python-mpdclient, python-lxml, python-httplib2, python-uritemplate, mpd, mpc, po-debconf, debconf, fonts-dejavu
Pre-Depends: libgtk2-perl, python-pip, alsa-utils
Recommends: python-rpi.gpio
Conflicts: youtube-dl
Description: Webradio Frontend for MPD
 Webradio.py is a Python script which is designed to be a full-screen or windowed Frontend for MPD (Music-Player-Daemon). It allows to manage webradio-stations and is capable to utilize the GPIO's when running on a Raspberry-Pi.
 .
 *    Search and manage webradio-stations with a GUI
 *    Listen to your local MP3-Music-Collection
 *    Search your MP3-Collection
 *    Automated Album-Cover download
 *    Use of embedded Album-Covers from your MP3's
 *    support for multiple File-Formats like .mp3, .ogg, .oga, and .flac
 *    Stream Music from Youtube
 *    Check the Weather-Forecast for you location
 *    Multiple and self-designable Themes
 *    Shutdown-Timer / Sleep-Timer
 *    GPIO integration (use Buttons for changing webradio-stations, shutdown, mount-/umount USB-Sticks aso.)
 *    Onscreen settings
 *    Screensaver-Mode
Homepage: https://my-darling-is-a-linux-user.org
root@webradio:/home#

**Comment by Acer54** [comment]
can you purge the installation with `apt purge webradio-py` ? If so, you can try to re-install it with `apt update && apt install webradio-py`

**Comment by omulverde** [comment]
I will try again. Thats way I said it is from hostname change maybe...
I can give you a conection to it if you want ....

**Comment by Acer54** [comment]
Please do not install as root! Log in as "pi" and start the installation process with "sudo" .... otherwise your user-folder might be placed in the wrong sub-folder (/home/root/.webradio)... but I am quite sure that your X-Server will be owned by "pi" and not root...

**Comment by omulverde** [comment]
OK. SURPRIZE: working!!!!
I have other problem: the screen is too small.....
if I want to go to settings I have to push on arow...

**Comment by Acer54** [comment]
Have you configured webradio-py to load in fullscreen? This should be a question during the install-process? If yes, and it still does not show up correctely, you can set to windowed mode with `sudo dpkg-reconfigure webradio-py` and selection "fullscreen, no". You can then try to work around such issues with hard-coding your resolution in ~/.webradio/webradio.conf   (Section "Forced Values" / "SCREENRESOLUTION") delete the "#" and type in your resolution.  
If the problem still persists, please open a new issue and upload a screenshot. 
If the installation issue was solved with the installation as user "pi", please close this issue.

**Comment by omulverde** [comment]
sudo dpkg-reconfigure webradio-py (fullscreen, no) YES is OK >>> WORKING
Do not solve problem >> SCREENRESOLUTION=720x480  (for original Pi lcd touchscreen)
I change Pi to diferent  resolution and nothing change. Touch work only on pictograms on different resolutions 
freeze in "Loading" after reboot no mather what Design/Template is ( I have to touch many times kb&mause to start). The image is bigger and not centrate.

Screen saver is not centrate on midle. It is in low part of screen and on the left part.
Only in Grunge pictograms are big and get out of screen. Pitty: I lake the most. In rest are OK.
Fallback is OK.Pi it is in default 720x480. Touch working OK.

**Comment by Acer54** [comment]
So, if you configure (sudo dpkg-reconfigure) to fullscreen, Yes, than it is OK? ...

Second isseu: For the bootup-issue, try to configure with "sudo raspi-config" in bootoptions to "wait for network".

**Comment by omulverde** [comment]
1.  wait for network=on; OK starts in 5 seconds; is the best
2. full screen on boot; OK but the pictogram are OK after change Design from Fallback to another template after bach to Tempalte fallback. Otherwise is out of screen Settings pictogram. Why?

Screen Saver only the clock and day is visible. Weather is not visible. I like weather.
Personal isue: font for clock is too small; background is beter to be darkness on all template.
When you find a radio, that "clepsidra" rounded get out of screen; is too big in the low part of the screen.

**Comment by omulverde** [comment]
Now, I will start to build box for radio. I'm sure working with same upgradable problems.
I saw you made it one. You use audio output direct from 3,5mm Pi audio out or from same soundcard?
The audio is OK?

**Comment by omulverde** [comment]
![template](https://user-images.githubusercontent.com/34549236/69914886-d6fc8000-1451-11ea-87e7-7f84930a13e6.jpeg)

**Comment by Acer54** [comment]
Do you still have this arrows after re-start of webradio-py? With small screen resolutions, this is necessary at some point.

**Comment by omulverde** [comment]
After change Design from Fallback to another template after bach to Tempalte fallback, disipear.
