### ISSUE TITLE
Audio OUT

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#44]
Now, I will start to build box for radio. I'm sure working with same upgradable problems.
I saw you made it one (or more). You use audio output direct from 3,5mm Pi audio out or from same soundcard?
The audio is OK?

**Comment by Acer54** [comment]
No, I use (with my webradio) output of a USB Soundcard (USB-Dongle) ... available for 3-4 €/USD all around the internet. From my point of view, audio-out from the build in 3.5mm jack is too bad at some point.
But ... is this a actual a webradio-py issue? Please only open issues, for issues caused or with webradio-py.
