### ISSUE TITLE
Screensaver during standby on original 800x480 Pi LCD (default 720x480)

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#45]
In Screen Saver only the clock and day is visible.
![ScreenSaver](https://user-images.githubusercontent.com/34549236/69914833-58074780-1451-11ea-80e1-7469f7b938a4.jpeg)

Weather is not visible. It is usefull to see weather.

**Comment by Acer54** [comment]
What are your current settings for screen-resolution? Please show:

- cat /etc/systemd/system/webradio.service
- cat ~/.webradio/webradio.conf |grep SCREEN_RESOLUTION

**Comment by omulverde** [comment]
pi@webradio:~ $ cat /etc/systemd/system/webradio.service 
[Unit]
Description=Webradio Frontend for MPD
Documentation=https://github.com/Acer54/Webradio_v2/wiki

# Having network in "Wants" is intentional, because we want webradio.py to start even when network is not available.
Wants=network.target network-online.target
Requires=sound.target
After=network.target network-online.target sound.target

[Service]
Environment="DISPLAY=:0"
Environment="XAUTHORITY=/home/pi/.Xauthority"
User=pi
Type=simple
ExecStart=/usr/bin/sudo /usr/bin/python /opt/webradio/webradio.py --touchscreen --fullscreen
RestartSec=5
Restart=on-failure
StartLimitInterval=20
StartLimitBurst=3

[Install]
WantedBy=graphical.target

**Comment by omulverde** [comment]
pi@webradio:~ $ cat ~/.webradio/webradio.conf |grep SCREEN_RESOLUTION
SCREEN_RESOLUTION=800x480

**Comment by Acer54** [comment]
Disable forced size-setting in webradio.conf by adding a '#' at beginning of line (#SCREEN....) After Restart of webradio-py, screensaver should adapt to Fullscreen. Weather will be fully visible then.

**Comment by omulverde** [comment]
Does not happend. Is the same.

**Comment by omulverde** [comment]
![b](https://user-images.githubusercontent.com/34549236/69916818-349bc700-1468-11ea-9ceb-e383f608bf72.jpeg)

Look at the clock.

**Comment by Acer54** [comment]
But what about the screensaver?

**Comment by omulverde** [comment]
Screensaver do not work normal.It is the same.

**Comment by Acer54** [comment]
Can you please provide a Screenshot of the whole Webradio-Screen (not Screensaver)? There must me something wrong with your resolution setting... nobody ever had this kind of problem (as far as I know)...

**Comment by omulverde** [comment]
![c](https://user-images.githubusercontent.com/34549236/69919137-90734980-1482-11ea-9538-7606eb87d943.jpeg)

**Comment by omulverde** [comment]
![d](https://user-images.githubusercontent.com/34549236/69919182-efd15980-1482-11ea-94ec-515da70a5567.jpeg)

**Comment by omulverde** [comment]
![e](https://user-images.githubusercontent.com/34549236/69919215-50f92d00-1483-11ea-82c4-599b4d8d5c7e.jpeg)

**Comment by omulverde** [comment]
![f](https://user-images.githubusercontent.com/34549236/69919413-27410580-1485-11ea-984c-c05e2df746ca.jpeg)

**Comment by omulverde** [comment]
![g](https://user-images.githubusercontent.com/34549236/69919501-1775f100-1486-11ea-8168-a30bc9c2ff07.jpeg)

**Comment by Acer54** [comment]
Sorry, cant help. Seems like there is something wrong with the calculation of the available Desktop-Size (which is done by Qt4, the window framework...) Cant say if it is an issue with your LCD setting or with webradio-py. One time, the Screensaver is a way to big, now it is to small. Looks like you are constantly trying different settings... I have lost the overview if I ever had one.

**Comment by omulverde** [comment]
I will try different setings may be solv the problem.

**Comment by Acer54** [comment]
Just searched the internet ... seems like Displays which are connected with a ribbon cable directly to a VGA Boards (not HDMI) are using a "stetched 720x480 resolution to meet 800x480" I think this might knock webradio-py calculations out.
I suggest to switch of "Fullscreen" (sudo dpkg-reconfigure webradio-py) and foce the correct value (720x480) in ~/.webradio/webradio.conf. This might lead to the desired result.

**Comment by omulverde** [comment]
********  Problem SOLVED  *********  (I didn't sleep till I solved)

Thanks to Matthias which open my mind I solved problem with original Pi LCD.
After 2 days of changing parameters, I found the best for this monitor.

Hardware:
Rasbbery Pi 3B+
Rasberian 10 Buster
original Rasberry 7" LCD 800x480

Software:
Webradio.py (installed with sudo not with root like I does >> wrong position of directories >> do not work)
LCD default resolution (set in Rasberry Pi Configuration >> set default 720x480)
sudo dpkg-reconfigure webradio-py (fullscreen >> NO)
 
sudo nano ~/.webradio/webradio.conf
At section "Forced Value" set  SCREENRESOLUTION=810x500 (no more no less; will cause freezing; if happend >> press Enter and wait)
If you asking why this values: because I tested and works; if you put 800 you will have a white line on left side of display; othewise not work
I hope I made myself understood and I will send in next comment foto with result of this configurations.

Result:
Webradio.py ScreenSaver works properly; if you want to stop Rasberry screensaver >> sudo apt install xscreensaver and stop it.
Webradio.py template looks normaly in any situation without arrows.
LCD Pi Touch works perfect.

**Comment by omulverde** [comment]
![r](https://user-images.githubusercontent.com/34549236/69969155-8c980380-1524-11ea-8838-751e94fb54fd.jpeg)


![t](https://user-images.githubusercontent.com/34549236/69969162-93267b00-1524-11ea-9018-5ec90fe4c9e3.jpeg)

**Comment by omulverde** [comment]
One problem:
"The Bomb" does not centrated in the midle and Shutdown buton is over....
But this is not a problem....

**Comment by Acer54** [comment]
Congratulations! Hope your solution is helpful for someone searching for it ;-)
The Time-Bomb is a little bit shifted to one side, this is because the window should adapt from very small resolutions (640x480) up to very big displays > 1024x780 ... its not so easy to align all of the different widgets that its beautifull with every display size...  so this is "normal" for the moment.
