### ISSUE TITLE
Online-Tracks are blocking UI when outdated tracks getting updated

### ISSUE THREAD

**Issue by Acer54** [Acer54/Webradio_v2#46]
Section "MP3 Player" freeze and it is not usable as soon as outdated online-tracks are in the media-playlist.

Expected behavior: Tracks should update in the background. Process should be in non-blocking thread. User should not get aware of the time which is needed to update all online-tracks.

_Originally posted by @omulverde in https://github.com/Acer54/Webradio_v2/issues/43#issuecomment-561513900_

**Comment by Acer54** [comment]
Created a hotfix for this issue (on Version 0.3.9) with https://github.com/Acer54/Webradio_v2/commit/244157767d0e8e3d8b77cdc67c760559f848140a

Included in this hotfix is the ro-translation (Romanian) and some other minor issues.

-> New installations will get the updated version by default, 
-> if someone experiance same problem, you can update your installation with `sudo apt --reinstall install webradio-py`
(config files will be kept...)

**Comment by omulverde** [comment]
OK. I will test it.
I already does update but no romanian translate present.
I think I have a broken install on my Rasberry.
I have to reinstall Rasberian and webradio.
Tomorow. Today I still work at prototipe plexiglass box for my son.
