### ISSUE TITLE
Frecvent frozen WebRadio

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#48]
comment this in webradio.conf. Most of you do not have this user.
 #MusicFolder=/home/matthias/Musik

**Comment by Acer54** [comment]
Webradio-py is supposed to run in armhf-devices (Raspberry Pi). If you are starting the skript with a manual installation on a x86 System, it will take the MusicFolder=/home/matthias/Musik (which is my own, on he development-machine).
So if you run it on a armhf, there is no need to comment this.

Whatever your previous problem was ... this was not a solution for it. 

Regards, Matthias
