### ISSUE TITLE
unbenutzter I/O 4

### ISSUE THREAD

**Issue by Radiofreund** [Acer54/Webradio_v2#5]
Hallo,
ich hab da einen Wunsch. kann man bei Inaktivität des Touch, nach einer einstellbaren Zeit einen Ausgang schalten?
Sowas hatt ich schon mal :-) in der ersten Version dank Matthias und es wäre für mich ein K.o. Kriterium gegen Version2.
Hintergrund: Mein LCD Touch geht nach knapp 10 min "aus". Also "aus" = nur die Anzeige, die Hintergrundbeleuchtung bleibt an, das sieht nicht nur komisch aus sondern nervt auch.
Ich konnte daher, nach einer einstellbaren Zeit die Spannungsversorgung der Hintergrundbeleuchtung über ein Relais aus - schalten und bei Berührung wieder an. Das Touch selber lief ja weiter.

Die erste Version läuft bei mir täglich mehrere Stunden Streß- und Fehlerfrei. Mich reizt lediglich das neue Design und 2-3 kleine Neckigkeiten... :-)

Trotzdem vielen Dank an Euch. Ich bin leider nicht der, der Euch helfen kann..., leider.
Ich bin daher hier nur ein "stiller" Mitleser.

**Comment by Acer54** [comment]
Hallo,

hierzu ist eigentlich das Relais3 vorgesehen. Dieses schaltet, sobald der Radio in den Standby geschaltet wird (über den Ein-/Aus Button). Eingestellt / aktiviert werden, kann das Relais mittels der Konfigurationsdatei ["webradio.conf"](https://github.com/Acer54/Webradio_v2/blob/master/webradio.conf) im Abschnitt GPIO-Out (hierzu muss die entsprechende Zeile nur auskommentiert werden).
Ich hoffe das ist was du meinst... 

Wenn wir damals bei der Version1 etwas "spezielles" gebastelt haben, müsstest du mir vielleicht deine funktionierende V1 nochmal zukommen lassen ... das lässt sich bestimmt auch in V2 adaptieren... So groß ist der Unterschied V1 - V2 nicht ;-)

**Comment by Radiofreund** [comment]
Hallo Acer54,
ja das war speziell... und aber auch genial für mich.
Mein Problem ist mein Panel..
- http://www.waveshare.com/wiki/7inch_HDMI_LCD_(B) -

Das hatt einen "integrierten" screensaver. Das heißt, die Anzeige geht aus, Hintergrund bleibt beleuchtet und erscheint während dem Betrieb hellgrau...
Sieht während dem Betrieb einfach nur Sch... aus.
Daher bräuchte ich einen screensaver für während dem Betrieb.
Ich schick Dir gerne noch mal meine aktuell betrieben und hochgeschätzte webradio.py Version1.
Vieleicht haben andere auch Interresse und man kann es permanent integrieren.
Danke

**Comment by Acer54** [comment]
Hallo Radiofreund,
ich habe dazu im Wiki gerade einen zusätzlichen [Artikel](https://github.com/Acer54/Webradio_v2/wiki/(optional)-Energy-Star---Bildschirmabschaltung-aufheben-verhindern) eingestellt, mit dem sich dieses Verhalten unterbinden lassen sollte.
Solltest du dennoch eine Lösung suchen, die nach einer gewissen Zeit einfach ein Relais schaltet, müsste ich dazu etwas programmieren. 
Gib Bescheid, wenn dir die Lösung aus dem Wiki ins Ziel gebracht hat, oder ob du hierzu ein Feature benötigst.

**Comment by Radiofreund** [comment]
Hallo Acer54,
das probier ich sofort aus. Das war mir so nicht bewußt, daß das nicht vom Panel selbst kommt.

Jetzt wirds aber richtig schick. 
Man startet das Radio läßt alles z.B. eine Stund laufen, schaltet den Bildschirm ab, Radio läuft weiter und bei Berührung kommt die Anzege wieder...
Wie gesagt, bei mir läufts den halben Tag und da hätt ich schon Interesse an dieser Funktion.
man hört ja zumeist radio und schaut weniger :-) 
Ich find zwar relevante Stellen in der version1 kriegs aber nicht in der version 2 zum laufen.
Ich schick Dir nochmal ne mail. Vielen Dank im vorraus.

**Comment by Radiofreund** [comment]
Matthias, vielen Dank für die Anleitung.

Probier ich aus. Ich habe auch mal geantwortet.

Und mein Wunsch würde bestehen bleiben.

 

Das sind die Stellen im alten webradio.py, wo ich meine die relevant sind.

Wie gesagt mein Horizont ist da zu tief….

 

class Screensaver_watchdog(QObject):

    '''

    This Object have to be installed to a Application and works like a monitor which works like well known Screensavers.

    It emits two kind of Signals which have to be connected to any function.

    '''

 

    screenSaver_on = pyqtSignal()   # turn on the screensaver if this signal occures

    screenSaver_off = pyqtSignal()  # turn off the screensaver if this signal occures

 

   def __init__(self, parent=None):

        super(Screensaver_watchdog, self).__init__(parent)

        self.active = False

 

        # Es wird ein Timer erstellt, welcher typischer Weise ein Signal namens "timeout()" aussendet, wenn dieser

        # abgelaufen ist. Siehe Dokumentation : http://doc.qt.io/qt-4.8/qtimer.html

        # Diese signal wird verbunden mit der Funktion "_on".

        self.timer = QTimer()

        self.connect(self.timer,SIGNAL("timeout()"), self._on)

 

    def eventFilter(self, receiver, event):             # ALLE Events die in der app auftreten laufen hier durch

        if event.type() == QEvent.MouseButtonPress:    # Wie sehen uns die MouseButtonPress Events an

            if self.active:                             # wenn der Screensaver gerade aktiv ist,

                self.screenSaver_off.emit()             # wird dieser ausgeschaltet

                self.active = False                     # wir merken uns den neuen Zustand

                self.restartTimer()                     # den Timer starten wir mal neu

                return True                             # "True" verhindert, dass das Event weiterverarbeitet wird

            else:                                       # Wenn allerdings kein Screensaver an ist,

                self.restartTimer()                     # wird einfach nur der Timer zurückgesetzt

                return super(Screensaver_watchdog,self).eventFilter(receiver, event)  # und der Event wird weiterverarbeitet

        else:

            return super(Screensaver_watchdog,self).eventFilter(receiver, event) # alle anderen Events auch....

 

    def _on(self):     # diese Funktion wird aufgerufen, wenn der Timer abläuft, also ein Reset durchgeführt wird bzw

        if not self.active:    # der Bildschirm nicht "berührt" wird.

            self.screenSaver_on.emit()   # wir emitieren ein Signal, das bedeutet, dass der Screensaver eingeschaltet werden soll

            self.active = True      # und merken uns den neuen Zustand.

 

    def restartTimer(self):    # Diese Funktion wird immer dann aufgerufen, wenn ein Klick erfolgt und der Screensaver aus ist

        if self.timer.isActive():  # wenn der Timer bereits läuft, wird er ersteinmal gestoppt

            self.timer.stop()

        self.timer.start()   # anschließend wieder gestartet

        self.active = False  # wir merken uns den Zustand (nicht unbedingt notwendig)

 

    def setInterval(self, seconds):

        self.timer.setInterval(int(seconds)*1000)

 

                                               

 

if __name__ == "__main__":

 

    ################################ Prepare Logger ######################################

    # create logger with '__name__'

    logger = logging.getLogger("webradio")

 

    logger.setLevel(logging.DEBUG)

    # create file handler which logs even debug messages

    fh = logging.FileHandler('webradio.log', mode="w")

    fh.setLevel(logging.DEBUG)

    # create console handler with a higher log level

    ch = logging.StreamHandler()

    ch.setLevel(logging.ERROR)

    if args.debug:

        ch.setLevel(logging.DEBUG)

    # create formatter and add it to the handlers

    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(filename)s - %(funcName)s - %(message)s')

    fh.setFormatter(formatter)

    ch.setFormatter(formatter)

    # add the handlers to the logger

    logger.addHandler(fh)

    logger.addHandler(ch)

    #####################################################################################

    # Append Errormessages to the logfile, if there are any ....

    #sys.stderr = open(os.path.join(cwd,"webradio.log"), 'a')

    if args.disable_gpio:

        GPIO_active = False

 

    app = QApplication(sys.argv)

    app.setOverrideCursor(QCursor(Qt.BlankCursor))     # new - testing

    splash = QSplashScreen(QPixmap(":/loading_wall.jpg"))

    splash.show()

    app.processEvents()

 

    mainwindow = MainWindow()

    myScreensaver = Screensaver_watchdog() # definiere den Screensaver_watchdog

    myScreensaver.setInterval(600) # Zeit

    app.installEventFilter(myScreensaver) # die Main-App bekommt den Eventfilter

 

    #  der Eventfilter gibt also 2 Signale aus, welche wir noch verbinden:

    myScreensaver.connect(myScreensaver, SIGNAL("screenSaver_on()"), mainwindow.RLCD_off) # Verbindung der Signale

    myScreensaver.connect(myScreensaver, SIGNAL("screenSaver_off()"), mainwindow.RLCD_on) # Verbindung der Signale

    myScreensaver.restartTimer()

 

    mainwindow.startup_actions()

    mainwindow.show()

    splash.finish(mainwindow)

    if args.fullscreen:

        mainwindow.showFullScreen()     # a fullscreen window at raspberry is 1024 x 600 (Splashscreen does not work)

 

    app.exec_()

 

 

Von: Laumer Matthias [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Dezember 2016 12:28
An: Acer54/Webradio_v2 <Webradio_v2@noreply.github.com>
Cc: Radiofreund <lis.koehler@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [Acer54/Webradio_v2] unbenutzter I/O 4 (#5)

 

Hallo Radiofreund,
ich habe dazu im Wiki gerade einen zusätzlichen Artikel <https://github.com/Acer54/Webradio_v2/wiki/(optional)-Energy-Star---Bildschirmabschaltung-aufheben-verhindern>  eingestellt, mit dem sich dieses Verhalten unterbinden lassen sollte.
Solltest du dennoch eine Lösung suchen, die nach einer gewissen Zeit einfach ein Relais schaltet, müsste ich dazu etwas programmieren.
Gib Bescheid, wenn dir die Lösung aus dem Wiki ins Ziel gebracht hat, oder ob du hierzu ein Feature benötigst.

**Comment by Acer54** [comment]
Hallo Radiofreund,

ich habe gerade eine neue Version von webradio.py und webradio.conf freigegeben, welche du herunterladen und austauschen müsstest. 
Es ist im Abschnitt "General" nun ein neuer Punkt hinzugekommen (der standardmäßig erst einmal auskommentiert ist, aber einfach durch entfernen des Doppelkreuzes aktiviert werden kann) bei dem du die Zeit in Sekunden angeben kannst, wann ein Displayschoner aktiv werden soll.
- wenn du das Relais3 aktiviert hast, wird dieses geschaltet, 
- wenn du den "Bildschirmschoner" aktiviert hast (über den Settingstab) wird ein "Displayschoner" ähnlich dem des Standbys angezeigt.

Ich arbeite z.Z. noch an einer Möglichkeit Youtube-Playlists im Media-Player ab zu spielen, weshalb ich hieraus kein "Release" machen will/kann, da einfach der Player noch nicht 100% fertig ist...

Schließe das Issue, wenn diese Version dein Problem löst.

Viele Grüße,
Acer54

**Comment by Radiofreund** [comment]
Ich traus mir fast gar nicht zu schicken….

 

 

Von: Laumer Matthias [mailto:notifications@github.com] 
Gesendet: Montag, 5. Dezember 2016 19:46
An: Acer54/Webradio_v2 <Webradio_v2@noreply.github.com>
Cc: Radiofreund <lis.koehler@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [Acer54/Webradio_v2] unbenutzter I/O 4 (#5)

 

Hallo Radiofreund,

ich habe gerade eine neue Version von webradio.py und webradio.conf freigegeben, welche du herunterladen und austauschen müsstest.
Es ist im Abschnitt "General" nun ein neuer Punkt hinzugekommen (der standardmäßig erst einmal auskommentiert ist, aber einfach durch entfernen des Doppelkreuzes aktiviert werden kann) bei dem du die Zeit in Sekunden angeben kannst, wann ein Displayschoner aktiv werden soll.

*	wenn du das Relais3 aktiviert hast, wird dieses geschaltet,
*	wenn du den "Bildschirmschoner" aktiviert hast (über den Settingstab) wird ein "Displayschoner" ähnlich dem des Standbys angezeigt.

Ich arbeite z.Z. noch an einer Möglichkeit Youtube-Playlists im Media-Player ab zu spielen, weshalb ich hieraus kein "Release" machen will/kann, da einfach der Player noch nicht 100% fertig ist...

Schließe das Issue, wenn diese Version dein Problem löst.

Viele Grüße,
Acer54

**Comment by Radiofreund** [comment]
Von: Laumer Matthias [mailto:notifications@github.com] 
Gesendet: Montag, 5. Dezember 2016 19:46
An: Acer54/Webradio_v2 <Webradio_v2@noreply.github.com>
Cc: Radiofreund <lis.koehler@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [Acer54/Webradio_v2] unbenutzter I/O 4 (#5)

 

Hallo Radiofreund,

ich habe gerade eine neue Version von webradio.py und webradio.conf freigegeben, welche du herunterladen und austauschen müsstest.
Es ist im Abschnitt "General" nun ein neuer Punkt hinzugekommen (der standardmäßig erst einmal auskommentiert ist, aber einfach durch entfernen des Doppelkreuzes aktiviert werden kann) bei dem du die Zeit in Sekunden angeben kannst, wann ein Displayschoner aktiv werden soll.

*	wenn du das Relais3 aktiviert hast, wird dieses geschaltet,
*	wenn du den "Bildschirmschoner" aktiviert hast (über den Settingstab) wird ein "Displayschoner" ähnlich dem des Standbys angezeigt.

Ich arbeite z.Z. noch an einer Möglichkeit Youtube-Playlists im Media-Player ab zu spielen, weshalb ich hieraus kein "Release" machen will/kann, da einfach der Player noch nicht 100% fertig ist...

Schließe das Issue, wenn diese Version dein Problem löst.

Viele Grüße,
Acer54
