### ISSUE TITLE
Sender wechseln willkürlich

### ISSUE THREAD

**Issue by mamer999** [Acer54/Webradio_v2#6]
Hallo,

zuerst mal, Super! Leider wechseln bei mir willkürlich die Sender, manchmal nur das Logo. Passiert z.B. bei mut/unmute. Buffer in mpd.config bereits gesetzt.

**Comment by Acer54** [comment]
Hallo Mamer999, es könnte sich um eine zu langsame Netzwerkverbindung handeln bzw. Abbrüche. Es gab auch schon erste Erfahrungswerte, dass MPD bei bestimmten Versionen herumzickt. Meist half ein Downgrade der MPD-Version. Hierzu findet sich ein Eintrag in den FAQ's im Wiki Bereich: [Link](https://github.com/Acer54/Webradio_v2/wiki/FAQ#thema-ffn-wird-nicht-abgespielt-bzw-wird-nach-kurzem-anspielen-gewechselt)
Wenn du sagst "willkürlich", dann meinst du, dass er auf "irgendwelche" Sender wechselt? Auf "andere" in deiner Favoriten-Liste? Oder auf den "nächsten" in deiner Favoriten-Liste? ... das wäre noch ganz hilfreich...

**Comment by mamer999** [comment]
Hallo Matthias,

eine langsame Netzwerkverbindung war sicher nicht das Problem, aber wohl tatsächlich die aktuelle Version von MPD. Nach dem Downgrade gemäß FAQ war das Problem verschwunden. Allerdings hatte ich vorher bei der Verwendung von MPD mittels MPC schon festgestellt, dass das Problem bei der aktuellen Version wohl in der Verwendung von M3U’s liegt, mit MP3-Urls lief alles problemlos.

Wenn Sender gewechselt wurden, dann bei mir tatsächlich „willkürlich“. Teilweise stimmten auch Sendername und Logo nicht mehr überein. Zu diesem Zeitpunkt waren nur drei Sender in den Favoriten.

Eine Anmerkung noch: Durch die in Deiner aktuellen Version verwendeten Checkbox „Onlineinhalte einbeziehen“ wird auf einem Standard-Raspberry-Display (7“, 800x480)  im Suchdialog die Bildschirmtastatur so zusammengeschoben, dass sie nicht mehr benutzt werden kann. Ich habe die Checkbox erstmal rausgenommen und in der Abfrage konstant „True“ gesetzt.

Ansonsten aber ein hervorragende Lösung, kann sogar von meiner Frau benutzt werden 😊!

Gruß

Jürgen (Mamer999)

Gesendet von Mail für Windows 10

Von: Laumer Matthias
Gesendet: Dienstag, 22. August 2017 17:08
An: Acer54/Webradio_v2
Cc: mamer999; Author
Betreff: Re: [Acer54/Webradio_v2] Sender wechseln willkürlich (#6)

Hallo Mamer999, es könnte sich um eine zu langsame Netzwerkverbindung handeln bzw. Abbrüche. Es gab auch schon erste Erfahrungswerte, dass MPD bei bestimmten Versionen herumzickt. Meist half ein Downgrade der MPD-Version. Hierzu findet sich ein Eintrag in den FAQ's im Wiki Bereich: Link
Wenn du sagst "willkürlich", dann meinst du, dass er auf "irgendwelche" Sender wechselt? Auf "andere" in deiner Favoriten-Liste? Oder auf den "nächsten" in deiner Favoriten-Liste? ... das wäre noch ganz hilfreich...
