### ISSUE TITLE
Umbauen von Button-Funktionen und weiteres

### ISSUE THREAD

**Issue by Bauingenieur** [Acer54/Webradio_v2#7]
Hallo ☺️ ,

Ich bin Feuer und Flamme für dein Radio! Wollte selber etwas machen habe es bis jetzt nicht wirklich geschafft. Danke dafür, dass du mir damit eine gute Starthilfe leistest!
An dem Radio würde ich gerne ein paar Veränderungen vornehmen, doch leider bin ich "neu" auf diesem Gebiet! Kannst du mir bei meinen Fragen weiter helfen?

- Ich möchte dem USB-Button eine andere Funktion zuweisen. Er soll nämlich an dieser Stelle AirPlay Musik abspielen (ja von meinem iPhone aus 😉). Somit müsste ich den USB Code ausklammern und durch den AirPlay ersetzten können. In welchen Dateien muss ich das alles erledigen? Ich blicke da noch nicht wirklich durch.
- Da ich leider Gottes schon ein Display gekauft habe und es "leider" nur 3.5" aber mit 480x800 Pixel bestückt ist, sind mir gewisse Buttons (zum Bsp. Lautstärkeregler) zu klein. Wo kann ich den Klick-Rahmen vergrössern? Liegt dies in der webradio.py Datei? Und muss ich dann für jedes Fenster dies neu Definieren?

Gruss der Bauing

**Comment by Acer54** [comment]
Hallo Bauing,

bzgl. deiner Frage nach dem GUI und den Widgets die du ändern willst, musst du dir die Files unter ui/ vornehmen. Unter dem Unterordner (ui_raw) findest du die ui files, welche du mit dem Qt4-Designer editieren kannst (aktuell ist flexi3.ui)... geladen wird allerdings Pythoncode aus ui/flexi.py 

Bzgl. deiner Frage wegen dem "USB-Button": Ich benutze den Ein-/Ausschalter in einer Doppelfunktion. (Lange drücken = Ausschalten, kurz drücken = USB Stick auswerfen) Schau dir mal das File "webradio.py" ab der Zeile 2661 ff an. ... hier könntest du das Verhalten dementsprechend anpassen.

Viel Erfolg,
Matthias
