### ISSUE TITLE
screensaver.py verursacht einen Konflikt mit dem Wetter

### ISSUE THREAD

**Issue by Phanthomas83** [Acer54/Webradio_v2#9]
Scheinbar hat Weather.com die WebSite überarbeitet.
Daher startet das WebRadio nicht mehr.

`2018-08-11 13:18:33,463 - ERROR - webradio.py - excepthook - Uncaught exception
Traceback (most recent call last):
  File "/home/pi/webradio/webradio.py", line 3895, in <module>
    mainwindow.startup_actions()
  File "/home/pi/webradio/webradio.py", line 959, in startup_actions
    __define_additional_widgets(self)
  File "/home/pi/webradio/webradio.py", line 452, in __define_additional_widgets
    self)
  File "/home/pi/webradio/lib/screensaver.py", line 43, in __init__
    self.startUpdate()  # start counters to periodically update conditions
  File "/home/pi/webradio/lib/screensaver.py", line 152, in startUpdate
    self.updateWeather() # initially make a call to the API to get the current condition
  File "/home/pi/webradio/lib/screensaver.py", line 174, in updateWeather
    temp_condition['current_conditions']['icon'], "static"))`

Die ID des Ortes ist nun anders (sehr lange ID : https://weather.com/de-DE/wetter/heute/l/260be5565c24d1b88f1fe9de63be1af523dd051924d2b08c6bc34aa411d7305f für Hohenstein-Ernstthal) und kann vom screensaver.py nicht verarbeitet werden.

Verübergehende Lösung für mich (damit das Radio wieder startet): 
self.updateWeather() auskommentieren mit #self.updateWeather()

Im WebRdaio selbst ist der Ort (wenn man ihn dort zuvor eingetragen hat) noch vorhanden und die Daten werden korrekt geladen.

**Comment by Acer54** [comment]
Danke für den Hinweis. Ich schaue mir das Ganze mal an, wenn ich wieder zuhause bin... bin momentan in Urlaub :-)

**Comment by Acer54** [comment]
Typischer Fall von "erledigt sich durch warten" :-) Anscheinend war es kein "Umbau" von weather.com, sondern lediglich eine Fehlfunktion. Nun, wo ich in der Fehlersuche schon recht tief drin war, scheint es ohne weiteres wieder zu funktionieren und auch die Testergebnisse im Code, liefern die Ergebnisse welche zu erwarten wären... Thema damit erledigt? Läuft es auch bei dir wieder ?

**Comment by Phanthomas83** [comment]
stimmt, funktioniert wieder. kann also gelöscht werden :-)

**Comment by Acer54** [comment]
Habe es heute auch nochmal gestestet. War anscheinend ein temporäres Problem bei weather.com
